version: "3"
services:
# Jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"

# Zipkin
  zipkin:
      container_name: zipkin
      image: openzipkin/zipkin:latest
      ports:
          - "9411:9411"
          - "9410:9410"

# Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

